USE `recipes`;

DROP TABLE IF EXISTS `recipe_classes`;
CREATE TABLE `recipe_classes`(
	`id` INT AUTO_INCREMENT,
	`description` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);

INSERT INTO `recipe_classes`(`description`)
	VALUES('Main Course'),
		  ('Vegetable'),
		  ('Starch'),
		  ('Salad'),
		  ('Hors d\'oeuvres'),
		  ('Dessert'),
		  ('Soup');

DROP TABLE IF EXISTS `recipes`;
CREATE TABLE `recipes`(
	`id` INT AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`recipe_classes_id` INT,
	`preparation` TEXT,
	`notes` TEXT,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`recipe_classes_id`) REFERENCES `recipe_classes`(`id`)
);

INSERT INTO `recipes` (`id`, `title`, `recipe_classes_id`, `preparation`, `notes`) VALUES
(1, 'Irish Stew', 1, 'Cut the beef into 1\" chunks\nBraise the meat\nAdd water and Guinness\nChop onions, potatoes, and carrots into 1/2\" chunks.\nAdd to stew.\nSimmer until vegetables are done.', NULL),
(2, 'Salsa Buena', 5, 'Coarsely dice the jalapenos .\nMix all ingredients thoroughly in a bowl and let stand in the refrigerator for about an hour. \nServe with your favorite corn chips.', NULL),
(3, 'Machos Nachos', 5, 'Slice the jalapenos crosswise (in circles) and set aside.\nGrate the cheddar cheese and set aside.\nDice the onion and set aside.\nSpread the tortilla chips on a large microwavable dish.\nTop the chips with the grated cheese, diced onion, and jalapenos.\nPlace the dish in the micowave and cook until the cheese just melts, about 3-4 minutes on high.\nWhen the cheese has melted, remove the dish and top with the black olives.', 'You can add a half a cup of diced tomatoes to this dish if you like. You can either add them prior to cooking in the microwave or afterwards, just before you add the black olives.'),
(4, 'Garlic Green Beans', 2, 'Snap off and discard the ends of the beans, then rinse them in cold water.\nMince the two cloves of garlic.\nHeat the oil in a frying pan on medium high heat.\nWhen the oil is hot, add the green beans and garlic. \nStir contiuously for about four minutes. \nPlace the beans on a serving dish when they\'re done and sprinkle silvered almonds on the top.', 'Be sure not to burn the oil. Watch it carefully while it\'s heating.'),
(5, 'Fettuccini Alfredo', 1, 'Fill a large pot two thirds full with water. Add one tablespoon each of salt and vegetable oil. Bring to a rollling boil.\nReduce heat, add pasta, and stir briefly. Cook until pasta is al dente.\nJust before the pasta is ready (about five minutes), melt the butter in a frying pan on low heat.\nAfter the butter has melted, add the heavy cream to the pan. Increase the heat to medium and stir until the mixture is slightly thickened. Remove the pan from the heat once the mixture is ready.\nDrain the fettuccini when it\'s done and add it to the mixture in the frying pan.\nMix three ounces of the cheese the the fettuccini and toss the entire mixture.\nAdd another three ounces of cheese and the white pepper, and toss again lightly.', NULL),
(6, 'Pollo Picoso', 1, 'Wash chicken pieces thoroughly in cold water. Pat dry and set aside.\nMince garlic and then mix it with the salt, pepper, and cayenne. Make sure the mixture is combined as thoroughly as possible.\nCoat each chicken piece (to taste) with the mixture. \nPlace pieces in the broiler pan and cook for 15 minutes. Turn pieces and cook for another 15 minutes. Turn pieces once more and cook for 35 - 40 minutes.\nWhen the chicken is cooked, remove from stove and let it stand for 10 minutes.', 'Pre-heat the oven to 400 degrees.\nCover the bottom of a broiler pan with a sheet of aluminum foil and then pour in about 1/2 an inch of water. The water will keep the chicken grease drippings from splattering throughout the inside of the stove and causing smoke. The foil makes the pan easier to clean.'),
(7, 'Mike\'s Summer Salad', 4, 'Rinse lettuce and cut into bite size pieces. (You can tear them if you really want to.)\nDust off mushrooms, remove stems, and slice into thick pieces, about 1/4\".\nPeel the cucumber and slice it into 1/4\" thick circles.\nSlice the tomatoes into 1/2\" wedges.\nWash radishes, remove leafy head and root, and slice into 1/8\" circles.\nMix all ingredients together in a large salad bowl and add your favorite balsamic vinaigrette dressing.', NULL),
(8, 'Trifle', 6, 'Prepare the Jello and custard per package directions.\nIn tall dessert cups, place a 1/2\" layer of the sponge cake.  Soak the layer of cake in Jello.  Spoon on a thin layer of raspberry jam.  Add a layer of custard.\nContinue adding layers of sponge cake, jam, and custard until the cup is full (with a layer of custard on top) -- 2 to 3 layers.\nChill for 2 hours.  Sprinkle colored sugar on top and serve.', 'For a \"spicier\" dessert, replace half the liquid in the Jello with brandy or your favorite liqueur.'),
(9, 'Roast Beef', 1, 'Place the beef on a roasting rack in a roasting pan.\nMake a paste of ground garlic, salt, and pepper.  Smother the outside of the roast with the paste.\nRoast at 325 for about 20 minutes per pound or to an internal temperature of 160F for medium-rare.\nRemove from oven and let stand 15 minutes before carving.  Reserve the beef drippings for gravy or Yorkshire Pudding.', NULL),
(10, 'Yorkshire Pudding', 3, 'Place the eggs and water in a blender.  While running the blender, slowly add the flour.  Add the salt and milk and blend for 30 seconds more.\nLet stand in a refrigerator for 1 hour or more.\nHeat the roasting pan with beef drippings to 450F.  Pour in the pudding mixture.  Cook in a very hot oven for 20-25 minutes or until puffed up and golden brown.  Remove from the pan immediately and cut into slices.  Serve with brown gravy.', NULL),
(11, 'Huachinango Veracruzana (Red Snapper, Veracruz style)', 1, 'Heat one ounce of olive oil in a 1.5 quart saucepan.  Slice the onion and sautee lightly in the olive oil.\nDrain the canned tomatoes (you can use peeled fresh tomatoes if you like) and puree in a blender.\nTo the pureed tomatoes, add all the spices, thinly sliced Jalapenos, and green olives.  Pour the tomato and spice mixture into the saucepan with the onions and simmer on a very low heat covered for 30 minutes.\nWhile the sauce is cooking, peel and boil the potatoes.\nJust before the potatoes are done, heat the remaining olive oil in a large frypan.  Wash and lightly dust the fish pieces in a mixture of flour, salt, and pepper.  Fry the fish, turning once, until just done.\nPlace the cooked fish in a large platter.  Surround the fish with the boiled potatoes.  Pour the sauce over the fish, sprinkle with chopped parsley, and serve immediately.\nServes 6.', 'You can substitute any firm white fish filets for the Red Snapper.  If you use salted canned tomatoes, reduce the salt in the sauce by half.  Adjust the amount of the Jalapenos in the sauce to suit your taste for spicy food!'),
(12, 'Asparagus', 2, 'Wash the asparagus and break off the tough part (if any) at the bottom of the stalks.  Arrange on a steaming rack in a large saucepan.  Dab liberally with pats of butter and sprinkle on the chopped garlic.  Steam until just tender -- no more than 5 minutes for large stalks.  Serve immediately.', 'You can chill the cooked asparagus and serve with your favorite dip as an appetizer.'),
(13, 'Tourti?re (French-Canadian Pork Pie)', 1, 'Brown ground pork and chopped onion, stirring and breaking up pork.  Add spices and salt and pepper.  Simmer, uncovered, for 45 minutes, stirring occasionally.  Preheat oven to 375 degrees.  Prepare pie dough for 2-crust pie.  Line 9\" pie plate with half of the rolled-out dough.  Drain pork and stir bread crumbs into pork.  Taste and add more salt and pepper if desired.  Fill pie with pork mixture and top with second half of the rolled-out dough.  Crimp edges of pie and slit the top in several places.  Bake in 375-degree oven for one hour, covering edges of pie crust with foil if necessary.  Serve hot or cold.', 'Be sure to use fresh ground pork, not sausage.  Can be made with half ground pork and half ground beef, if desired.'),
(14, 'Salmon Filets in Parchment Paper', 1, 'Julienne carrots, leeks, and bell peppers and steam for several minutes.  Drain and rinse vegetables in ice water and set aside.  Preheat oven to 400 degrees.  Butter 4 large rounds of parchment paper.  Distribute half of vegetables on one side of each round of parchment.  Place a salmon filet on the vegetables on each round.  Top the filets with the rest of the vegetables.  Combine white wine and lemon juice and spoon 1 tablespoon on each filet.  Pour melted butter on filets.  Place a thinly-sliced lemon round on each.  Salt and pepper very lightly.  Fold over parchment paper into half circles and roll and crimp edges tightly.  Bake packets at 400 degrees for 10-15 minutes, depending on thickness of the filets.', 'Serve the salmon in the parchment packets. A salad and boiled new potatoes, buttered and sprinkled with fresh parsley, are the perfect complements.'),
(15, 'Coupe Colonel', 6, 'For each person, place 2 scoops of lemon sorbet in a stemmed glass.  Top with vodka.', 'This is a lovely, light, and refreshing dessert.  Use the best sorbet and vodka you can find.  Serve with crisp cookies.');